repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/cpplint/cpplint
  rev: 1.6.1
  hooks:
    - id: cpplint
      args: ["--filter=-legal/copyright"]
- repo: https://github.com/clang-format/clang-format
  rev: v18.1.8
  hooks:
    - id: clang-format
      files: \.(c|cc|cpp|h|hpp|hh)$
